### ISSUE TITLE
1.8.0: Ad's now opening in safari 

### ISSUE THREAD

**Issue by bcaufield** [appcelerator-modules/ti.admob#16]
It looks like the default behavior for opening ads has changes as of 1.8.0 - previously the ad would default to opening in an app-hosted overlay window but now ads are opening in safari on iOS. I looked for a parameter to control this behavior but I can't find anything. In admob documentation, there is a reference to admob.opener.openOverlay() function that accepts a boolean - is this currently exposed and if not how hard would it be to do that?

**Comment by hansemannn** [comment]
Hi @bcaufield, that behavior is handled by the Admob SDK internally. We just call the SDK methods internally.
