### ISSUE TITLE
Module is not supported By Titanium SDK 3.4.1GA

### ISSUE THREAD

**Issue by rushingfitness** [appcelerator-modules/ti.admob#18]
When I look at the TiApp Editor for tiapp.xml, I see that this module is greyed out and has a warning sign. On hover it prints outs 'The "ti.admob' module is not supported By Titanium SDK 3.4.1GA".

If I try to run the app I get the following error:
`[ERROR] :  Could not find all required Titanium Modules:`
`[ERROR] :     id: ti.admob	 version: latest	 platform: iphone	 deploy-type: development`

What am I missing?

And yes I did pull down the latest from master as a zip and installed it successfully as a module (at least it said it did, I can't find it when I try to add a mobile module).

Also I installed SDK 3.3.0RC (Couldn't find a 3.3.0GA download anywhere) and still had the issues above.

**Comment by PSGRaptor** [comment]
rushingfitness: Did you ever get the module to work properly? I've been working on this all weekend and keep getting:
Message: Uncaught Error: Requested module not found: ti.admob even though in tiapp.xml Overview ti.admob is showing installed and the little cube is green. This is extremely frustrating.

**Comment by PSGRaptor** [comment]
Ingo: If you're watching this I am using the ti.admob module from github also. v2.1.2.
Building for Android on Windows 8.1 
Ti Studio 3.4.1.GA

Modules section of tiapp.xml

    <modules>
        <module deploy-type="development" platform="android">ti.admob</module>
        <module deploy-type="production" platform="android">ti.admob</module>
        <module platform="android">ti.map</module>
        <module platform="android">ti.compression</module>
    </modules>

**Comment by rushingfitness** [comment]
@PSGRaptor if you look at my previous post, I ended up getting a third party to send me the correct file structure. For whatever reason when I downloaded the files directly from github through titanium, it wouldn't structure the files correctly. So unfortunately I don't have an answer to this.

**Comment by PSGRaptor** [comment]
@rushingfitness so what you are saying is you found an alternative that does work properly with Ti Studio 3.4.1.GA? You found someone with a repaired structured module that works? Or you never got Admob to work inside your App. I did look at your post but you didn't say if the third party data helped. If you got it to work I'd appreciate you letting us know how you accomplished it.

**Comment by rushingfitness** [comment]
Yes, their file structure worked. I removed the folders that were created when I downloaded and installed via Titanium. Then I took the third parties folders and put them in the correct location (On Mac, idk about Linux or Win). The real key seems to be that when downloaded through Titanium, it's not correctly importing the correct file structure for admob. Idk why this happens, I'm very much a noob with Titanium, though I've been coding for years so I understand most of this stuff. If needed I can put up a repo that has the correct files and folders and tell where to add them in your folder structure (pending its the same as mine, as well as the same OS). Let me know if this will help

**Comment by PSGRaptor** [comment]
@rushingfitness Yes, please post the correct file structure or a package where the file structure is working, this would help all of us figure out what the problem is. ASAP Please

**Comment by jonalter** [comment]
@rushingfitness @PSGRaptor could you describe the process (that didn't work) that you followed to install the module so we can track down the issue?

##### Follow the steps below to install the module in the correct location:
1. Go to the **Releases** section of the github repo for the module that you want to install https://github.com/appcelerator-modules/ti.admob/releases
2. Choose the latest version (in this case iOS v1.9.0), right click the green download button, and click *Copy Link Address*
3. In Studio click on *Help > Install Mobile Module...*
4. Paste the link you copied into "Install from URL:"
5. For "Output Location" you have 3 options, but lets just focus on the first 2
 * **Titanium SDK** - Select this option if you would like the module to be installed in a location were all Titanium applications can use it (eg. `/Users/jalter/Library/Application\ Support/Titanium/modules/iphone/ti.admob/1.9.0`)
 * **Mobile App Project:** - Select this option if you want the module to be installed and only available for one app (eg. `/Users/jalter/Documents/Titanium\ Studio\ Workspace/Test/modules/iphone/ti.admob/1.9.0`). You will need to select the app from the dropdown. 
6. Click *Ok*
7. You can now check in the location that you selected to install the module to make sure that it is there. Use the example paths above as reference.

Let me know how it goes.

**Comment by rushingfitness** [comment]
hey @jonalter, so I followed option 1. I did everything that you said there so I could access it from any app I build. After though when I look at the ui manifest on the right side, I see that the admob is listed (since I added to manifest.xml), but it greyed out. If I remove the admob from the list and try to add from the UI, it doesn't show in the available list to use on my app. If I go to the actual folder where it has been installed, I see that the folder is not actually in the modules folder as a child folder, but as a sibling folder. That being said if I move the folder to inside the modules folder, the link appears in the available module section, (You would think hooray, it was just installed in the wrong directory) but when I try to run the app, I get an error saying admob couldn't run. Basically the files aren't even correct. Very strange, not sure why this happens. It's a clean install of Titanium, latest version etc. No custom mods or anything. Hope this helps to diagnose. Let me know if you need anymore info

**Comment by jonalter** [comment]
@rushingfitness, a few more questions.
1. Can you be more specific about the name of the folder that is being installed next to the `modules` folder? Also, could I get the full path to your modules folder?
2. Could you paste the error that you are seeing when you run the app after moving the folder into the `modules` folder?
3. For testing purposes, please make a new app, install the module in that app's folder, specify the version of the module that you are trying to run, use the example app that comes with the module, and if that doesn't work, please zip up that whole project and post a link here to the zip so I can try it.

**Comment by rushingfitness** [comment]
1.) @jonalter I don't want to try and redownload it because I have it working now and honestly don't want to mess with the file structure and frantically try and fix it. So I can't tell you what the error was. If memory serves me correctly, it said a file was missing.

2.) As far as file structure, I have a folder called Titanium Modules in my Downloads folder that holds all modules I have imported. It's split into two folders, iphone and android.

This is how it's supposed to look:
-Titanium Modules
 > --iphone
    > -- ti.admob
 > -- android
    > --ti.admob

This is how it look when I imported via Titanium and latest zip file from your github:
-Titanium Modules
 > --iphone
    > -- random module
 > -- android
    > --random module
 > --ti.admob


3.) I can do that later today, at work right now coding business stuff. When I get home I can try step 3 for you

**Comment by jonalter** [comment]
@rushingfitness,
1. Okay, I definitely understand. Don't worry about this one for now.
2. It is interesting that you have your installed modules in a folder in your `Downloads` folder. By default modules are only searched for in `~/Library/Application\ Support/Titanium/` and in the root of your application. This may be part of the problem. What did you do to change the location that modules are installed and searched for?
3. Sounds good. Thank you sir.

**Comment by rushingfitness** [comment]
2. Oh nope you were right, I have that and that's where I meant to reference, not in the downloads folder. My bad. So I'm uploading a screenshot of how it is now (correct)

![screen shot 2015-01-12 at 9 43 26 pm](https://cloud.githubusercontent.com/assets/3672033/5715261/1bf86e12-9aa4-11e4-9af5-e8b4b550b816.png)

For when it downloaded through Titanium it looked like this...

![screen shot 2015-01-12 at 9 44 15 pm](https://cloud.githubusercontent.com/assets/3672033/5715263/326c5744-9aa4-11e4-9271-8e45115b2208.png)

**Comment by rushingfitness** [comment]
And sorry I go busy building a golang web scraper last night for my startup. I'll try to get to your testing tonight

**Comment by jonalter** [comment]
Ah I see! thank you for the screen shots. Can you tell me what **versions** you are using of: 
* Appcelerator Studio (Appcelerator Studio in the menu bar > About Appcelerator Studio)
* Titanium SDK (The SDK version selected in your tiapp.xml)
* Titanium CLI (from the terminal `$ ti -v`)
* Admob Module
 * Are you downloading the module from https://github.com/appcelerator-modules/ti.admob/releases ?

When you get a second don't forget to provide the steps you followed to install the module when it went in the wrong location.

No problem. That sounds good.

Thanks for your help!

**Comment by rushingfitness** [comment]
1: (I use Titanium studio, not appcelerator studio, idk if this is the same) 
    - Titanium Studio, build: 3.4.1.201410281727
2: 3.4.1.GA
3: 3.4.1
4: Yes

**Comment by rushingfitness** [comment]
Well. Weirdly enough, I just tried to use the install module and inserted the iphone and android links, and they both worked. Not sure what changed, maybe was a bad version it was trying to pick up a bad version or something. Not sure, but it works now. Thanks for the help. I'm going to close this as it looks like it's fixed.
