### ISSUE TITLE
No interstitial ad displayed

### ISSUE THREAD

**Issue by fcjurado** [appcelerator-modules/ti.admob#2]
I'm trying to display an interstitial ad, but nothing happens. On console log I had:

[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[INFO] :   Ads: Starting ad request.
[INFO] :   Ads: Use AdRequest.Builder.addTestDevice("***") to get test ads on this device.
[INFO] :   Ads: No fill from ad server.
[INFO] :   Ads: Scheduling ad refresh 60000 milliseconds from now.

It seems that I've to install Google Play Services, but I've it installed yet on my phone. It was tested on two Android phones, one with Android 4.2 and other with Kit Kat. My app.js:

var win = Titanium.UI.createWindow({  
    backgroundColor:'#000'
});

var Admob = require('ti.admob');

setTimeout(function(){
	show_interstitial();
},5000);

win.open({animated: true});

function show_interstitial(){
	var adMobInterstitial = Admob.createView({
	    publisherId:"ca-app-pub-3192763241213853/**********",
	    testing: false , // default is false
	    top: 0,
	    width: Ti.UI.FILL,
	    height: Ti.UI.FILL,
	});
	win.add(  adMobInterstitial );
}

[Update] If instead an Interstitlal ad, I change the publisherId by a normal ad, ads are displayed. So, It seems to be an issue with interstitials.

Why I have to addTestDevice if testing is false? And why any ad is shown? Thanks in advance.

The form in admob.com is so simple:

![captura de pantalla 2014-09-29 a la s 12 35 48](https://cloud.githubusercontent.com/assets/1314788/4440433/409412da-47c5-11e4-8af6-0dc848f0a8cd.png)

**Comment by hansemannn** [comment]
Please follow https://github.com/appcelerator-modules/ti.admob/issues/20 for further discussion.
