### ISSUE TITLE
Smart Banner Ads

### ISSUE THREAD

**Issue by PSGRaptor** [appcelerator-modules/ti.admob#23]
Is there a parameter  available to request "smart banner" ads that use the whole device width? right now I have only been able to produce a banner ads that is approx. 320 width on a tablet this is very small and not very useful.

**Comment by hansemannn** [comment]
Hi @PSGRaptor ! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)

You can just specify a height now and the width is calculated automatically. Let me know if it works for you.

**Comment by hansemannn** [comment]
Closing this issue. The new version has been released yesterday and includes an example on how to use different kind of ads. Thanks everyone for testing!
