### ISSUE TITLE
Add iAd adapter to Admob module

### ISSUE THREAD

**Issue by Astrovic** [appcelerator-modules/ti.admob#26]
Admob require an adapter for iAd mediation. This can be found here: https://dl.google.com/dl/googleadmobadssdk/libadapteriad.zip
Is there any plan to add this library to the Admob module, otherwise how can I add it? This would be very useful :)

**Comment by iRonin** [comment]
+1

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator-modules/ti.admob/pull/47, thanks!
