### ISSUE TITLE
Support for Interests?

### ISSUE THREAD

**Issue by bcaufield** [appcelerator-modules/ti.admob#28]
I have a client that needs to target ads based on name value pairs, e.g. "app"="first-load". from the admob documentation, it looks like there is a propery called "Interests" that supports this functionality - are there any plans to expose this? It looks like older versions of this module had a property called "extras" that would provide this functionality but that doesn't seem to be supported in this version. Please let me know if this is possible via another property or if we can get this feature added.

Thanks,

Brian Caufield

**Comment by bitfabrikken** [comment]
Haven't heard any plans for this, but you could do what I did with regards to interstitial ads - hire a freelancer on e.g. freelancer.com to make it, then share it here as a pull request for everyone else :)

**Comment by bcaufield** [comment]
Thanks bitfabrikken, its nice to get some kind of response - I was thinking the issues section has been abandoned.

**Comment by bcaufield** [comment]
After reviewing the admob SDK, it looks like a better approach to target ads would be via the "extras" property as defined in the GADRequest.h:
- (void)registerAdNetworkExtras:(id<GADAdNetworkExtras>)extras;
Is this exposed via the module and if not, what would it take to do that?

Thanks,

Brian Caufield

**Comment by bcaufield** [comment]
I forked this module and added the support for DFPExtras which gives us the ability to send an extras object with the ad request. the fork is located here: [https://github.com/bcaufield/ti.admob] (https://github.com/bcaufield/ti.admob). I hope other people find this useful.

**Comment by hansemannn** [comment]
Hi everyone! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)

It covers some new prooerties including the `extras` property to handle an object of keys and values.
