### ISSUE TITLE
Script Error Couldn't find module: ti.admob for architecture: x86_64

### ISSUE THREAD

**Issue by deckameron** [appcelerator-modules/ti.admob#29]
I am using Ti.Admob 1.9.0 for iOS but I see this error everytime I compile with Titanium 3.5.0 SDK.

**Comment by sbmhome** [comment]
Did you ever fix this issue?

I currently have the same problem and can't find a solution.

**Comment by sbmhome** [comment]
Ok, I found the issue. 

it just wasn't finding the module. Had nothings to do with 64-bit support

**Comment by phanii** [comment]
wat is the solution then?? its not working on IOS latest versions, how can we resolve this issue;....

**Comment by hansemannn** [comment]
Hi everyone! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)
