### ISSUE TITLE
adMob SDK needs to be updated to 7.0

### ISSUE THREAD

**Issue by stephenfeather** [appcelerator-modules/ti.admob#31]
```
<Google:HTML> You are currently using version 6.12.0 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 7.0.0, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.
```

Release Notes: https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes
Download Page: https://developers.google.com/mobile-ads-sdk/docs/admob/ios/download

**Comment by deckameron** [comment]
@sfeather,
Does Google punish apps with old admob sdk's? Do we get lousy ads because of using 6.12.0?

**Comment by dlewis23** [comment]
@deckameron 

You get worse performance. On iOS 8 ads tend to take a while to load or I've noticed will not load at all. Admob SDK 7.0.0 fixes this. So it would be good to get it updated.

**Comment by tkrz** [comment]
yes it would be nice if this module got update to the latest SDK for admob.

**Comment by iRonin** [comment]
+1

**Comment by nuno** [comment]
+1  and for android too please. :)

**Comment by ashcoding** [comment]
Anyone opened a ticket for this yet? :)

**Comment by ashcoding** [comment]
I created a ticket here: https://jira.appcelerator.org/browse/MOD-2158
Feel free to comment on it and watch it.

**Comment by nazrdogan** [comment]
+1

**Comment by hansemannn** [comment]
Hi everyone! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)

**Comment by deckameron** [comment]
Feel free to try this one!
https://github.com/deckameron/Ti.Android.Admob

**Comment by hansemannn** [comment]
Should be resolved by https://github.com/appcelerator-modules/ti.admob/pull/63, please follow-up there, thx!
