### ISSUE TITLE
bitfabrikken intersitital issue on ios 8

### ISSUE THREAD

**Issue by elberto** [appcelerator-modules/ti.admob#32]
ad is received but I get no visible ad. A transparent layer appears preventing the phone from receiving events.
Works fine in ios 7 though.

*** WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <NSInvalidArgumentException> -[UIWindow presentViewController:animated:completion:]: unrecognized selector sent to instance 0x7bf77d80

**Comment by dlewis23** [comment]
I'm having a similar issue. I am able to receive an AD no problem but sometimes I get this error on device.

*** WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <NSInvalidArgumentException> -[UIWindow presentViewController:animated:completion:]: unrecognized selector sent to instance 0x12650bb10

**Comment by dlewis23** [comment]
After playing with this some more this error seems to only happen when the device orientation changes. My app is always one way but I can't find out how to make the interstitial stop rotating when its displayed.

**Comment by hansemannn** [comment]
Hi everyone! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)

**Comment by deckameron** [comment]
@hansemannn Thank you very much for your help.
Do you have an example of a intersitital ad on iOS, please?

**Comment by hansemannn** [comment]
@deckameron The updated module is for this branch, the bitfabrikken module is a fork.

**Comment by hansemannn** [comment]
Closing this issue (finally). The new version has been released yesterday and includes an example on how to use different kind of ads.
