### ISSUE TITLE
iOS 8 issue admob module

### ISSUE THREAD

**Issue by vivekgidmare** [appcelerator-modules/ti.admob#34]
<Google:HTML> You are currently using version 6.12.0 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 7.1.0, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.

**Comment by balanza** [comment]
Is there any progress over this issue? Actually is impossible to run admob on iOS with Titanium....

**Comment by nuno** [comment]
Hello, I can confirm, this module is not work on ios 8x, I tested some patch here but sill can't get the add, something changed in admob side? Thanks.

**Comment by phanii** [comment]
hi nuno ,
even i am also trying to resolve .. But its AdMob side ..how did u worked ? what is that patch .. any help is appreciated.

**Comment by phanii** [comment]
Even this module (1.6.0)  is working under 5S, But its saying that some architectural issue.
If you have any idea pls suggest me ...

**Comment by hansemannn** [comment]
Hi everyone! Please try the latest (prerelease) version that was published today: [Ti.Admob iOS 2.0.0](https://github.com/appcelerator-modules/ti.admob/releases/download/ios-2.0.0/ti.admob-iphone-2.0.0.zip)

**Comment by hansemannn** [comment]
Hey there, all iOS 8 has been resolved in the latest update 2.0.0.
