### ISSUE TITLE
Google Cookie Law EU?

### ISSUE THREAD

**Issue by Astrovic** [appcelerator-modules/ti.admob#39]
Last month, Google sent a mail to those who use AdMob, AdSense, Analytics for the new Google Cookie Law EU.
Some of you are adopting these new changes on your applications? What to do? Display a pop-up? Or what? Still I did not see any app that displays this message.

This is the mail:

> Dear Publisher,
>
>We want to let you know about a new policy about obtaining EU end-users' consent that reflects regulatory and best practice guidance. It clarifies your duty to obtain end-user consent when you use products like Google AdSense, DoubleClick for Publishers, and DoubleClick Ad Exchange.
>
>Please review our new EU user consent policyas soon as possible (https://www.google.com/about/company/user-consent-policy.html). This requires that you obtain EU end users' consent to the storing and accessing of cookies and other information, and to the data collection, sharing, and usage that takes place when youuse Google products. It does not affect any provisions on data ownership in your contract.
>
>Please ensure that you comply with this policy as soon as possible, and not later than 30th September 2015.
>
>If your site or app does not have a compliant consent mechanism, you should implement one now. To make this process easier for you, we have compiled some helpful resources at http://www.cookiechoices.org/ .
>
>This policy change is being made in response to best practice and regulatory requirements issued by the European data protection authorities. These requirements are reflected in changes recently made 
on Google's own websites.
>
>Thank you in advance for your understanding and cooperation.
>
>Regards,
The Google Policy Team

**Comment by hansemannn** [comment]
It looks like a change of the google polity which you need to accept on Google's website. It does not affect the functionality of this module.
