### ISSUE TITLE
Interstitial ads is possible?

### ISSUE THREAD

**Issue by kerbooo** [appcelerator-modules/ti.admob#43]
I read some post but I can't understand clearly, is it possible Interstitial ads with this ti.admob? If yes how can I implement to android and ios? is there any example?

Thank you in advance.

@sgtcoolguy @hansemannn

**Comment by hansemannn** [comment]
@kerbooo It will be in the next version which is currently work in progress (https://github.com/appcelerator-modules/ti.admob/pull/42)

**Comment by danny005** [comment]
Sound great. Both for iOS and Android? Have only seen the updates for iOS to support interstitial ads.

**Comment by hansemannn** [comment]
Alright guys, solved my problems with interstitional ads and updated https://github.com/appcelerator-modules/ti.admob/pull/42/. Please test the PR and the version [ti.admob-iphone-2.0.0.zip](https://github.com/appcelerator-modules/ti.admob/files/105889/ti.admob-iphone-2.0.0.zip). This PR only supports it for iOS, hopefully some Android developer can deliver the other part. Since it's open source, feel free to contribute!

**Comment by ottopic** [comment]
Are you sure that it works? 
For me in 2.0.0 interstitial doesn't works. Where is finished isInterstitial param ?

**Comment by hansemannn** [comment]
@ottopic Please check the included example.js which uses the updated API methods.

**Comment by ottopic** [comment]
Sorry, I have downloaded 2.0.0 from releases and it contain a different code!

**Comment by MushoodMunir** [comment]
@hansemannn Are you sure included example in 2.0.0 release also works for displaying interstitial ads?
How can i modify example code to display interstitial ads as well? It seems that example is still for banner ads. Can you tell what parameters to change?
`win.add( ad = Admob.createView({
	top : 0,
	height : 50,
	debugEnabled : true, // If enabled, a dummy value for `adUnitId` will be used to test
	adUnitId : '<<YOUR ADD UNIT ID HERE>>', // You can get your own at http: //www.admob.com/
	adBackgroundColor : 'black',
	testDevices : [Admob.SIMULATOR_ID], // You can get your device's id by looking in the console log
	dateOfBirth : new Date(1985, 10, 1, 12, 1, 1),
	gender : Admob.GENDER_MALE, // GENDER_MALE or GENDER_FEMALE, default: undefined
	contentURL : 'https://admob.com', // URL string for a webpage whose content matches the app content.
	requestAgent : 'Titanium Mobile App', // String that identifies the ad request's origin.
	extras : {// Object of additional infos
		"version" : 1.0,
		"name" : "My App"
	},
	tagForChildDirectedTreatment : false, // http:///business.ftc.gov/privacy-and-security/childrens-privacy for more infos
	keywords : ['keyword1', 'keyword2']
}));`

**Comment by MushoodMunir** [comment]
@hansemannn Are you sure included example in 2.0.0 release also works for displaying interstitial ads?
How can i modify example code to display interstitial ads as well? It seems that example is still for banner ads. Can you tell what parameters to change?
`win.add( ad = Admob.createView({ top : 0, height : 50, debugEnabled : true, // If enabled, a dummy value foradUnitIdwill be used to test adUnitId : '<<YOUR ADD UNIT ID HERE>>', // You can get your own at http: //www.admob.com/ adBackgroundColor : 'black', testDevices : [Admob.SIMULATOR_ID], // You can get your device's id by looking in the console log dateOfBirth : new Date(1985, 10, 1, 12, 1, 1), gender : Admob.GENDER_MALE, // GENDER_MALE or GENDER_FEMALE, default: undefined contentURL : 'https://admob.com', // URL string for a webpage whose content matches the app content. requestAgent : 'Titanium Mobile App', // String that identifies the ad request's origin. extras : {// Object of additional infos "version" : 1.0, "name" : "My App" }, tagForChildDirectedTreatment : false, // http:///business.ftc.gov/privacy-and-security/childrens-privacy for more infos keywords : ['keyword1', 'keyword2'] }));
`

**Comment by ottopic** [comment]
@MushoodMunir you have downloaded wrong version too. Donwload 2.0.0 from the link posted by @hansemannn 2 days ago.

**Comment by hansemannn** [comment]
@MushoodMunir @ottopic: The 2.0.0 was released a bit too early. Once it's merged, I will update the 2.0.0 release page as well. For now, please see the example.js from the above linked file (2 days ago). It shows, that interstitial views need to call `ad.receive()`, since it is handled different. The example.js shows a detailed example of both usages (banner and interstitial). Hope that helps.

**Comment by hansemannn** [comment]
Closing this issue (finally). The new version has been released yesterday and includes an example on how to use different kind of ads. Thanks everyone for testing!
