### ISSUE TITLE
Unable to submit app on itunes with ti.admob 2.0.0 ios?

### ISSUE THREAD

**Issue by MushoodMunir** [appcelerator-modules/ti.admob#44]
I am unable to submit app on itunes with ti.admob latest 2.0.0 module.  Interstitial ads are working great but when validating archive for my app during submission process  it has couple of issues. 1) Always receive itunes Authentication failed. The request timeout. Error After taking too long to validate. Same app with ti.admob 1.9.0 validates in 5-8 minutes successfully. 2) I able to validate archive successfully with 2.0.0 ti.admob version only once. But then this error shows app when submitting ipa through Application Loader "myAppName.app/GoogleMobileAds.framework/GoogleMobileAds is not permitted. Your app can't contain standalone executables libraries, or other than CFBundleExecutable of supported bundles " . Is someone else has submitted app with ti.admob 2.0.0 successfully?  I am building app with xCode 7.2, Ti.sdk 5.1.2, iOS v9.2

**Comment by ottopic** [comment]
@MushoodMunir @muhammaddadu I have the same problem!

**Comment by MushoodMunir** [comment]
@hansemannn Any progress on this??

**Comment by hansemannn** [comment]
@MushoodMunir @ottopic Currently investigating, it was weekend. Looks like the ".framework" is copied into the actual device build, but it shouldn't.

**Comment by hansemannn** [comment]
Please try using this version here (with just minor changes in the build configuration): 
[ti.admob-iphone-2.0.1.zip](https://github.com/appcelerator-modules/ti.admob/files/112087/ti.admob-iphone-2.0.1.zip)

**Comment by MushoodMunir** [comment]
@hansemannn Thanks. Working well now.
