### ISSUE TITLE
Update SDK for Android Version

### ISSUE THREAD

**Issue by jaridl** [appcelerator-modules/ti.admob#5]
I have been getting a message in Admob when logging into my account that says:  "On August 1, 2014, Google Play will stop accepting new or updated apps that use the old standalone Google Mobile Ads SDK v6.4.1 or lower."  The current module is using 6.2.1.  The iOS version was already updated to a more recent version.  Can someone update the Android version?

**Comment by hansemannn** [comment]
Please follow https://github.com/appcelerator-modules/ti.admob/issues/31 for further discussions, thanks!
